### Question 1 (Comparison of array)

In [2]:
import numpy as np
np_array1 = np.array([[1,2,3],[5,6,7]])
np_array2 = np.array([[8,9,0],[1,6,7]])
print("Array 1:",np_array1)
print("Array 2:",np_array2)
print("\nGreater:",np.greater(np_array1,np_array2))
print("\nGreater Equals:",np.greater_equal(np_array1,np_array2))
print("\nLess:",np.less(np_array1,np_array2))
print("\nLess Equal:",np.less_equal(np_array1,np_array2))



Array 1: [[1 2 3]
 [5 6 7]]
Array 2: [[8 9 0]
 [1 6 7]]

Greater: [[False False  True]
 [ True False False]]

Greater Equals: [[False False  True]
 [ True  True  True]]

Less: [[ True  True False]
 [False False False]]

Less Equal: [[ True  True False]
 [False  True  True]]


### Question 2 (Zeros, Ones, Fives)

In [9]:
np_zeros = np.zeros(10)
print("ZEROS:",np_zeros)

np_ones = np.ones(10)
print("Ones:",np_ones)

np_fives = np.ones(10) * 5
print("Fives:",np_fives)

ZEROS: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ZEROS: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
ZEROS: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### Question 3 (Sum of all elements, each row and each column)

In [4]:
import numpy as np
np_array = np.array([[3,4,5],[6,7,8],[10,7,23]])
print("Array:\n",np_array)
print("Sum of all elements:",np.sum(np_array))
print("Row wise sum:", np.sum(np_array,axis=1))
print("Column wise sum:", np.sum(np_array,axis=0))


Array:
 [[ 3  4  5]
 [ 6  7  8]
 [10  7 23]]
Sum of all elements: 73
Row wise sum: [12 21 40]
Column wise sum: [19 18 36]


### Question 4 (Add Subtract Multiply Divide)

In [8]:
np_array1 = np.array([[3,4,5],[6,7,8],[10,7,23]])
np_array2 = np.array([[7,8,0],[2,3,4],[1,0,4]])

print("ADD:\n", np.add(np_array1,np_array2))
print("Subtract:\n",np.subtract(np_array1,np_array2))
print("Multiply:\n",np.multiply(np_array1,np_array2))
print("Divide:\n",np.divide(np_array1,np_array2))

ADD:
 [[10 12  5]
 [ 8 10 12]
 [11  7 27]]
Subtract:
 [[-4 -4  5]
 [ 4  4  4]
 [ 9  7 19]]
Multiply:
 [[21 32  0]
 [12 21 32]
 [10  0 92]]
Divide:
 [[ 0.42857143  0.5                inf]
 [ 3.          2.33333333  2.        ]
 [10.                 inf  5.75      ]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys


### Question 5 (Sin, Cos, Tan)

In [24]:
np_array = np.array([90,60,120,45,30])

np_sin = np.array([])
np_cos = np.array([])
np_tan = np.array([])
for i in np_array:
    np_sin = np.append(np_sin,[np.sin(i)])
    np_cos = np.append(np_cos,[np.cos(i)])
    np_tan = np.append(np_tan,[np.tan(i)])

print("Sin:\n",np_sin)
print("Cos:\n",np_cos)
print("Tan:\n",np_tan)

Sin:
 [ 0.89399666 -0.30481062  0.58061118  0.85090352 -0.98803162]
Cos:
 [-0.44807362 -0.95241298  0.81418097  0.52532199  0.15425145]
Tan:
 [-1.99520041  0.32004039  0.71312301  1.61977519 -6.4053312 ]
